export const db_offline_placeholders = [
	"The database went out for coffee",
	"Our folders are currently playing hide and seek",
	"Fetching failed… probably tripped on a cable",
	"The database hit snooze. Again.",
	"Your files are in another castle",
	"Folders went on a vacation without telling us",
	"The file gnomes are being uncooperative today",
	"Database said 'brb' and never came back",
	"We yelled into the void. It yelled back. No folders.",
	"Folders? Yeah, they ghosted us",
	"The folders unionized. No work without snacks",
	"Database is buffering... in real life",
	"It's not a bug, it's a surprise feature",
	"Folders slipped into another dimension",
	"A wild 500 error appeared!",
	"The backend needs a backend massage",
	"Sorry, our file elves are on a coffee break",
	"The database tripped over a semicolon",
	"Our server ran out of digital duct tape",
	"We opened the folder... it was empty and judging us",
];

export const fetch_success_placeholders = [
	"Data fetched. The pixels rejoice",
	"Your request returned with snacks",
	"Fetched fresh and served hot",
	"Success! The bits are in your favor",
	"The network elves delivered",
	"Everything came back in one piece",
	"Got it! Like a digital carrier pigeon",
	"The fetch succeeded. Your data says hi",
	"Operation complete. Nothing exploded",
	"Victory! Even the backend is impressed",
	"Success! And we didn't even bribe the server",
	"Fetched and fabulous",
	"The API gods smiled upon you today",
	"Boom! Data landed like a boss",
	"Packets traveled far and wide... and made it!",
	"Success: The database handshake was firm",
	"Fetched it like it's hot",
	"Like clockwork — data's back",
	"Everything's in sync. Probably a glitch",
	"Fetched with flair",
	"Got what you asked for — and then some",
	"Return of the fetch",
	"Database: 1, Latency: 0",
	"Request fulfilled. Somewhere, a server smiled",
	"Shhh... the data is resting safely in state",
	"Mission accomplished, Captain",
	"Fetch successful. No abductions occurred",
	"The digital carrier raven returned safely",
	"Just in time — data beat the deadline",
	"Server says: 'You're welcome.'",
];
	
export const empty_folder_placeholders = [
	"Looks like this place is still under construction",
	"So empty, you can hear an echo... echo... echo",
	"This folder is emptier than your coffee cup",
	"Nothing here yet — but it has potential!",
	"No files? No worries. Just vibes",
	"Like a blank canvas. Time to get creative",
	"This folder is as empty as a politician's promise",
	"Still waiting for the first upload...",
	"It's lonely in here",
	"Not even a single byte in sight",
	"A ghost town of folders",
	"Clean, clear, and under control",
	"This folder is more organized than your desktop",
	"Folder status: Single and ready to mingle",
	"Quiet. Too quiet...",
	"Vacancy available — rent free",
	"No files yet. But the potential is *unlimited*",
	"Storage space? You've got plenty",
	"Nothing but digital tumbleweeds",
	"Someone forgot to pack the folder",
	"Folder's feeling a little empty. Want to fix that?",
	"You found the hidden land of Nothingness",
	"The great void of files awaits",
	"Just a folder, doing its best",
	"Empty folder — a minimalist's dream",
	"Airbnb for files. No guests yet",
	"Look at all this... space!",
	"It's like a fridge at the end of the month",
	"A pristine digital haven",
	"The calm before the upload",
    "This folder is running on pure potential energy"
];

export const loading_placeholders = [
	"Loading... Hold on to your folders.",
	"Fetching data... May take a byte.",
	"Still spinning... unlike your fan.",
	"Unzipping the internet...",
	"Charging the hamsters...",
	"Loading... our engineers are napping.",
	"Retrieving results from the void...",
	"Decrypting jokes... please wait.",
	"Spinning up some magic...",
	"Getting our digital ducks in a row...",
	"Compiling witty comment...",
	"Making API calls... and a few texts to mom.",
	"Negotiating with the backend...",
	"Rendering suspense... literally.",
	"Running on JavaScript and coffee...",
	"Waiting for Promise.resolve()...",
	"This is what async looks like.",
	"Loading... like a React app without hydration.",
	"Still faster than a cold start.",
	"Waiting on some bits to fall into place...",
	"Organizing virtual cabinets...",
	"Digitally dusting your folders...",
	"Loading files... Ctrl + Z not available.",
	"Unpacking digital boxes...",
	"Shuffling through the cloud...",
	"Almost there... like your pizza guy.",
	"Not stuck. Just deeply thinking...",
	"Loading... consider petting a dog.",
	"Please wait... or don't. I'm not your boss.",
	"Insert dramatic loading music here...",
	"Plotting the shortest path through your data...",
	"Taming wild bytes...",
	"Sneaking past firewalls...",
	"Taking a short nap... for performance.",
	"Looking busy while loading...",
	"Turning caffeine into JSON...",
	"Brewing some data... medium roast.",
	"Rounding up stray packets...",
	"Summoning data spirits...",
	"Locating the meaning of life... and your files.",
];

export const upload_success_placeholders = [
	"Uploaded faster than you can say 'byte me'",
	"File successfully beamed into the cloud",
	"Upload complete — zero packets were harmed",
	"Your file is now living its best digital life",
	"Like a boss — upload finished",
	"Cloud: 1, Gravity: 0",
	"The file flew up and stuck the landing",
	"Mission accomplished — file touched the sky",
	"Your upload just leveled up",
	"That file is now 100% more cloud-enabled",
	"Upload complete. Time to celebrate with a coffee",
	"Your file passed the vibe check",
	"Upload was smoother than a fresh jar of Skippy",
	"All systems green. Upload successful",
	"Your file just earned its wings",
	"Uploaded — it's not rocket science, but that was still cool",
];

export const upload_failure_placeholders = [
	"Upload failed — file took a wrong turn at Albuquerque",
	"The cloud sneezed. Try again",
	"Oops... your file ghosted us mid-upload",
	"Upload tripped over a 404",
	"File said 'nope' halfway through",
	"Upload failed. Even the bytes are confused",
	"The file tried to escape. We almost had it",
	"We lost the file in the cloud somewhere",
	"Well... that didn't go according to plan",
	"The upload fell into a digital black hole",
	"RIP to that file. It never stood a chance",
	"Upload failed — we blame gremlins",
	"The server just rage quit mid-upload",
	"File got stage fright and refused to go up",
	"The cloud coughed. File didn't make it",
	"Upload crashed harder than my Monday motivation",
];

