export const db_offline_placeholders = [
	"The database went out for coffee",
	"Our folders are currently playing hide and seek",
	"Fetching failed… probably tripped on a cable",
	"The database hit snooze. Again.",
	"Your files are in another castle",
	"Folders went on a vacation without telling us",
	"The file gnomes are being uncooperative today",
	"Database said 'brb' and never came back",
	"We yelled into the void. It yelled back. No folders.",
	"Folders? Yeah, they ghosted us",
	"The folders unionized. No work without snacks",
	"Database is buffering... in real life",
	"It's not a bug, it's a surprise feature",
	"Folders slipped into another dimension",
	"A wild 500 error appeared!",
	"The backend needs a backend massage",
	"Sorry, our file elves are on a coffee break",
	"The database tripped over a semicolon",
	"Our server ran out of digital duct tape",
	"We opened the folder... it was empty and judging us",
];

export const fetch_success_placeholders = [
	"Data fetched. The pixels rejoice",
	"Your request returned with snacks",
	"Fetched fresh and served hot",
	"Success! The bits are in your favor",
	"The network elves delivered",
	"Everything came back in one piece",
	"Got it! Like a digital carrier pigeon",
	"The fetch succeeded. Your data says hi",
	"Operation complete. Nothing exploded",
	"Victory! Even the backend is impressed",
	"Success! And we didn't even bribe the server",
	"Fetched and fabulous",
	"The API gods smiled upon you today",
	"Boom! Data landed like a boss",
	"Packets traveled far and wide... and made it!",
	"Success: The database handshake was firm",
	"Fetched it like it's hot",
	"Like clockwork — data's back",
	"Everything's in sync. Probably a glitch",
	"Fetched with flair",
	"Got what you asked for — and then some",
	"Return of the fetch",
	"Database: 1, Latency: 0",
	"Request fulfilled. Somewhere, a server smiled",
	"Shhh... the data is resting safely in state",
	"Mission accomplished, Captain",
	"Fetch successful. No abductions occurred",
	"The digital carrier raven returned safely",
	"Just in time — data beat the deadline",
	"Server says: 'You're welcome.'",
];
	
export const empty_folder_placeholders = [
	"Looks like this place is still under construction",
	"So empty, you can hear an echo... echo... echo",
	"This folder is emptier than your coffee cup",
	"Nothing here yet — but it has potential!",
	"No files? No worries. Just vibes",
	"Like a blank canvas. Time to get creative",
	"This folder is as empty as a politician's promise",
	"Still waiting for the first upload...",
	"It's lonely in here",
	"Not even a single byte in sight",
	"A ghost town of folders",
	"Clean, clear, and under control",
	"This folder is more organized than your desktop",
	"Folder status: Single and ready to mingle",
	"Quiet. Too quiet...",
	"Vacancy available — rent free",
	"No files yet. But the potential is *unlimited*",
	"Storage space? You've got plenty",
	"Nothing but digital tumbleweeds",
	"Someone forgot to pack the folder",
	"Folder's feeling a little empty. Want to fix that?",
	"You found the hidden land of Nothingness",
	"The great void of files awaits",
	"Just a folder, doing its best",
	"Empty folder — a minimalist's dream",
	"Airbnb for files. No guests yet",
	"Look at all this... space!",
	"It's like a fridge at the end of the month",
	"A pristine digital haven",
	"The calm before the upload",
    "This folder is running on pure potential energy"
];
